(function() {var implementors = {};
implementors["secrets"] = [{text:"impl&lt;'_, T:&nbsp;<a class=\"trait\" href=\"secrets/traits/trait.Bytes.html\" title=\"trait secrets::traits::Bytes\">Bytes</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"secrets/secret/struct.RefMut.html\" title=\"struct secrets::secret::RefMut\">RefMut</a>&lt;'_, T&gt;",synthetic:false,types:["secrets::secret::RefMut"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> + <a class=\"trait\" href=\"secrets/traits/trait.Bytes.html\" title=\"trait secrets::traits::Bytes\">Bytes</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"secrets/secret_box/struct.SecretBox.html\" title=\"struct secrets::secret_box::SecretBox\">SecretBox</a>&lt;T&gt;",synthetic:false,types:["secrets::secret_box::SecretBox"]},{text:"impl&lt;'_, T:&nbsp;<a class=\"trait\" href=\"secrets/traits/trait.Bytes.html\" title=\"trait secrets::traits::Bytes\">Bytes</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"secrets/secret_box/struct.Ref.html\" title=\"struct secrets::secret_box::Ref\">Ref</a>&lt;'_, T&gt;",synthetic:false,types:["secrets::secret_box::Ref"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> + <a class=\"trait\" href=\"secrets/traits/trait.Bytes.html\" title=\"trait secrets::traits::Bytes\">Bytes</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"secrets/secret_vec/struct.SecretVec.html\" title=\"struct secrets::secret_vec::SecretVec\">SecretVec</a>&lt;T&gt;",synthetic:false,types:["secrets::secret_vec::SecretVec"]},{text:"impl&lt;'_, T:&nbsp;<a class=\"trait\" href=\"secrets/traits/trait.Bytes.html\" title=\"trait secrets::traits::Bytes\">Bytes</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"secrets/secret_vec/struct.Ref.html\" title=\"struct secrets::secret_vec::Ref\">Ref</a>&lt;'_, T&gt;",synthetic:false,types:["secrets::secret_vec::Ref"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
